### PR TITLE
Update qr_painter.dart

### PR DESCRIPTION
**Pull request by stevenosse**
Added a fix for the bug "Future<Image> can't be assigned to Image"

### CODE REVIEW

**Comment by lukef** [comment]
This old one again. Is this because you're using an older version of dart/flutter? If so, you will need to pin to the older version of qr.flutter. 

You can check the issues and the 4-5 other PRs that have been closed for details on why this isn't merged.

**Comment by stevenosse** [comment]
I'm using flutter 1.5 stable. Mais fix worked for me

**Comment by lukef** [comment]
The latest version should work on 1.5+. Are you having an issue?

**Comment by stevenosse** [comment]
Was having the issue I tried to fix.
The fix worked for me and I was trying to help.

**Pull request closed without merging**
