### PR TITLE
Add styling option for Eye shape and data module shapes

### PR DESCRIPTION
**Pull request by ankur2136**

### CODE REVIEW

**Comment by mehmetf** [comment]
@lukef Could you please take a look at this? Thanks!

**Comment by lukef** [comment]
The reason I held off approving/merging this PR was because I was hoping to combine it with color styling to allow you to change the eye + data modules independently as it's requested quite frequently.

We would then deprecate `foregroundColor` for the most part. 

Is this something you'd be willing to make a change to support?

**Comment by ankur2136** [comment]
Sure I will send another PR by eod

**Comment by lukef** [comment]
This one is not require now, right?

**Pull request closed without merging**
